# https://travis-ci.org/jkbrzt/django-settings-export
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
env:
  - DJANGO=Django==1.5
  - DJANGO=Django==1.6
  - DJANGO=Django==1.7
  - DJANGO=Django
script:
  - pip install $DJANGO coverage
  - pip install .
  - coverage run --source=. --omit=setup.py ./demo/manage.py test --verbosity=2
after_success:
  - pip install python-coveralls
  - coveralls
