# https://travis-ci.org/jakubroztocil/django-settings-export
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
  - pypy3
env:
  - DJANGO=Django==1.5
  - DJANGO=Django==1.6
  - DJANGO=Django==1.7
  - DJANGO=Django
script:
  - pip install $DJANGO
  - pip install .
  - python ./demo/manage.py test --verbosity=3
after_success:
  - pip install python-coveralls
  - coveralls
